# Generated by Django 6.1 on 2026-08-29 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('code_type', models.CharField(choices=[('partner', 'Channel Partner'), ('customer', 'End Customer')], max_length=10)),
                ('owner_name', models.CharField(blank=True, max_length=150)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('product', models.CharField(choices=[('careertrek', 'CareerTrek'), ('marketscope', 'Marketscope'), ('recruitscope', 'Recruit Scope')], max_length=20)),
                ('discount_percent', models.PositiveIntegerField(default=5)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved - Live'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_codes', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_codes', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(max_length=254)),
                ('product', models.CharField(choices=[('careertrek', 'CareerTrek'), ('marketscope', 'Marketscope'), ('recruitscope', 'Recruit Scope')], max_length=20)),
                ('discount_applied', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('converted', 'Converted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='referrals.referralcode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_snapshot', models.CharField(blank=True, max_length=30)),
                ('action', models.CharField(choices=[('requested', 'Code Requested'), ('approved', 'Code Approved'), ('rejected', 'Code Rejected'), ('edited', 'Code Edited'), ('deactivated', 'Code Deactivated'), ('deleted', 'Code Deleted'), ('redeemed', 'Code Redeemed At Checkout'), ('user_created', 'User Account Created')], max_length=15)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('referral_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='referrals.referralcode')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_products', models.JSONField(blank=True, default=list, help_text='Product codes this user may generate referral codes for.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
