# Generated by Django 6.1 on 2026-08-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
