# Generated by Django 6.1 on 2026-08-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_alter_referralcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcode',
            name='active',
            field=models.BooleanField(default=True, help_text='Live codes can be deactivated without changing their approval history.'),
        ),
    ]
