# Generated by Django 6.1 on 2026-09-10 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_alter_auditlog_id_alter_partneronboardingrequest_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarterCouponIssuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(max_length=50)),
                ('external_user_id', models.CharField(max_length=100)),
                ('external_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter_issuances', to='referrals.referralcode')),
            ],
            options={
                'unique_together': {('source_system', 'external_user_id')},
            },
        ),
    ]
