# Generated by Django 6.1 on 2026-09-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0005_startercouponissuance'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneronboardingrequest',
            name='deactivation_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='startercouponissuance',
            name='deactivation_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
