# Generated by Django 6.1 on 2026-09-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0006_partneronboardingrequest_deactivation_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneronboardingrequest',
            name='application_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
