# Generated by Django 6.1 on 2026-09-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0007_partneronboardingrequest_application_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='external_order_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='referralcode',
            name='origin_system',
            field=models.CharField(choices=[('hub', 'Referral Hub'), ('wix', 'Wix / CareerTrek')], default='hub', max_length=10),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('requested', 'Code Requested'), ('approved', 'Code Approved'), ('rejected', 'Code Rejected'), ('edited', 'Code Edited'), ('deactivated', 'Code Deactivated'), ('deleted', 'Code Deleted'), ('redeemed', 'Code Redeemed At Checkout'), ('user_created', 'User Account Created'), ('wix_sync_failed', 'Wix Sync Failed'), ('wix_coupon_synced_in', 'Coupon Created From Wix'), ('wix_coupon_updated_in', 'Coupon Updated From Wix')], max_length=25),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(condition=models.Q(('external_order_id', ''), _negated=True), fields=('referral_code', 'external_order_id'), name='unique_external_order_per_code'),
        ),
    ]
