# Generated by Django 6.1 on 2026-09-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0009_purchaserewardissuance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('requested', 'Code Requested'), ('approved', 'Code Approved'), ('rejected', 'Code Rejected'), ('edited', 'Code Edited'), ('deactivated', 'Code Deactivated'), ('deleted', 'Code Deleted'), ('redeemed', 'Code Redeemed At Checkout'), ('user_created', 'User Account Created'), ('wix_sync_failed', 'Wix Sync Failed'), ('wix_coupon_synced_in', 'Coupon Created From Wix'), ('wix_coupon_updated_in', 'Coupon Updated From Wix'), ('leadgen_delivery_failed', 'Lead Gen Delivery Failed')], max_length=25),
        ),
    ]
