# Generated by Django 6.1 on 2026-09-16 09:58

from datetime import timedelta

import referrals.models
from django.db import migrations, models


def backfill_expiry(apps, schema_editor):
    """For already-approved codes, backdate expires_at to approved_at + 3
    years rather than migration-run-time + 3 years, so existing live
    coupons don't all suddenly expire 3 years from whenever this migration
    happens to run instead of 3 years from when they were actually approved."""
    ReferralCode = apps.get_model("referrals", "ReferralCode")
    for code in ReferralCode.objects.filter(approved_at__isnull=False):
        code.expires_at = code.approved_at + timedelta(days=365 * 3)
        code.save(update_fields=["expires_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0010_add_leadgen_delivery_failed_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcode',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=referrals.models.default_expiry, help_text='Coupon stops being redeemable after this date. Defaults to 3 years from approval; admins can extend or shorten it.', null=True),
        ),
        migrations.RunPython(backfill_expiry, migrations.RunPython.noop),
    ]