# Generated by Django 6.1 on 2026-09-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0011_add_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partneronboardingrequest',
            name='product',
            field=models.CharField(blank=True, choices=[('kareertrek', 'KareerTrek'), ('marketscope', 'Marketscope'), ('recruitscope', 'Recruit Scope')], max_length=20),
        ),
        migrations.AlterField(
            model_name='referral',
            name='product',
            field=models.CharField(choices=[('kareertrek', 'KareerTrek'), ('marketscope', 'Marketscope'), ('recruitscope', 'Recruit Scope')], max_length=20),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='origin_system',
            field=models.CharField(choices=[('hub', 'Referral Hub'), ('wix', 'Wix / KareerTrek')], default='hub', max_length=10),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='product',
            field=models.CharField(choices=[('kareertrek', 'KareerTrek'), ('marketscope', 'Marketscope'), ('recruitscope', 'Recruit Scope')], max_length=20),
        ),
    ]
