# Generated by Django 6.1 on 2026-09-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0012_alter_partneronboardingrequest_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='origin_system',
            field=models.CharField(choices=[('hub', 'Referral Hub'), ('leadgen', 'Lead Gen Tool'), ('wix', 'Wix / KareerTrek')], default='hub', max_length=10),
        ),
    ]
